services:
  certify-nft-api1:
    container_name: certify-nft-api1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
    env_file:
      - .env
    networks:
      - certify-nft-network

networks:
  certify-nft-network:
    external: true